version: '2'
services:
  db:
    image: postgres:9.6.9
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  challenge:
    image: challenge
    restart: always
    environment:
      DATABASE_CONN_URL: postgresql+psycopg2://postgres:postgres@db
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db/challenge
    ports:
      - 80:80
